FROM nginx:mainline-alpine
RUN rm /etc/nginx/conf.d/*
ADD wassup.conf /etc/nginx/conf.d/
ADD index.html /usr/share/nginx/html/
ADD index.css /usr/share/nginx/html/
ADD nyx.jpg /usr/share/nginx/html/
ADD lily.jpg /usr/share/nginx/html/
ADD penny.jpg /usr/share/nginx/html/
ADD snowden.jpg /usr/share/nginx/html/
ADD vampireeyes.jpg /usr/share/nginx/html/
ADD susan.jpg /usr/share/nginx/html/
ADD smokey.jpg /usr/share/nginx/html/
ADD pudge.jpg /usr/share/nginx/html/
ADD scout.jpg /usr/share/nginx/html/
